version: '2.1'

services:
  activemq:
    hostname: activemq
    image: webcenter/activemq
    ports:
      - 61616:61616
      - 8161:8161
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    restart: always
    volumes:
      - ./data/activemq:/data/activemq
      - ./var/log/activemq:/var/log/activemq
    networks:
      - my-network

  db:
    image: mysql:latest
    platform: linux/x86_64
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_DATABASE=test1
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks:
      - my-network

  train:
    image: train:0.0.1-SNAPSHOT
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test1?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_ACTIVEMQ_BROKER-URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - db
      - activemq
    networks:
      - my-network
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://train:8080/actuator/health" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  scoreboard:
    image: scoreboard:0.0.1-SNAPSHOT
    restart: always
    environment:
      SERVER_PORT: 8888
      LOGGING_LEVEL_COM_TASKSBB_SCOREBOARD: debug
      SPRING_ACTIVEMQ_BROKER-URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
      TRAIN_MS_URL: http://train:8080
    ports:
      - 8888:8888
    depends_on:
      - activemq
#       train:
#         condition: service_healthy
    networks:
      - my-network

  train-client:
    image: train-client:latest
    restart: always
    environment:
      API_URL: http://192.168.0.49:8080
    ports:
      - 4203:4201
    networks:
      - my-network

  scoreboard-client:
    image: scoreboard-client:latest
    restart: always
    environment:
      API_URL: http://192.168.0.49:8888
    ports:
      - 4204:4201
    networks:
      - my-network

networks:
  my-network:
